# Generated by Django 3.2.8 on 2021-11-12 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircraftdetail',
            name='engine',
        ),
        migrations.RemoveField(
            model_name='historicalaircraftdetail',
            name='engine',
        ),
        migrations.DeleteModel(
            name='Engine',
        ),
    ]
