# Generated by Django 4.0.6 on 2022-07-25 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalaircraft',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical aircraft', 'verbose_name_plural': 'historical aircrafts'},
        ),
        migrations.AlterModelOptions(
            name='historicalaircraftassembly',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical aircraft assembly', 'verbose_name_plural': 'historical aircraft assemblys'},
        ),
        migrations.AlterModelOptions(
            name='historicalaircraftcomponent',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical aircraft component', 'verbose_name_plural': 'historical aircraft components'},
        ),
        migrations.AlterModelOptions(
            name='historicalaircraftdetail',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical aircraft detail', 'verbose_name_plural': 'historical aircraft details'},
        ),
        migrations.AlterModelOptions(
            name='historicalaircraftmastercomponent',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical aircraft master component', 'verbose_name_plural': 'historical aircraft master components'},
        ),
        migrations.AlterModelOptions(
            name='historicalaircraftmodel',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical aircraft model', 'verbose_name_plural': 'historical aircraft models'},
        ),
        migrations.AlterField(
            model_name='aircraftcomponent',
            name='description',
            field=models.CharField(blank=True, help_text='Specify an internal description for this component e.g: x-2', max_length=140, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='aircraftcomponent',
            name='master_component',
            field=models.ForeignKey(blank=True, help_text='If no supplier exists, use the master component', null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.aircraftmastercomponent', verbose_name='Master Component'),
        ),
        migrations.AlterField(
            model_name='historicalaircraft',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalaircraftassembly',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalaircraftcomponent',
            name='description',
            field=models.CharField(blank=True, help_text='Specify an internal description for this component e.g: x-2', max_length=140, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalaircraftcomponent',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalaircraftdetail',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalaircraftmastercomponent',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalaircraftmodel',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
