# Generated by Django 2.1.2 on 2018-10-10 13:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_auto_20181002_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rpas',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.IntegerField(choices=[(0, 'NA'), (1, 'Open'), (2, 'Specific'), (3, 'Specific')], default=0),
        ),
        migrations.AddField(
            model_name='contact',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='role_type',
            field=models.IntegerField(choices=[(0, 'Other'), (1, 'Responsible')], default=0),
        ),
        migrations.AddField(
            model_name='operator',
            name='company_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='pilot',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rpas',
            name='esn',
            field=models.CharField(default='000000000000000000000000000000000000000000000000', max_length=48),
        ),
        migrations.AlterField(
            model_name='authorization',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 10, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='operator',
            name='operator_type',
            field=models.IntegerField(choices=[(0, 'NA'), (1, 'LUC'), (2, 'Non-LUC')], default=0),
        ),
    ]
