# Generated by Django 2.1.7 on 2019-03-27 11:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_auto_20181010_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(default='NA', max_length=140)),
                ('common_name', models.CharField(default='NA', max_length=140)),
                ('acronym', models.CharField(default='NA', max_length=10)),
                ('role', models.CharField(default='NA', max_length=140)),
                ('country', models.CharField(default='NA', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='RpasTypeCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_certificate_id', models.CharField(max_length=280)),
                ('type_certificate_issuing_country', models.CharField(max_length=280)),
                ('type_certificate_holder', models.CharField(max_length=140)),
                ('type_certificate_holder_country', models.CharField(max_length=140)),
            ],
        ),
        migrations.RenameField(
            model_name='authorization',
            old_name='area_type',
            new_name='operation_area_type',
        ),
        migrations.AddField(
            model_name='authorization',
            name='operation_altitude_system',
            field=models.IntegerField(choices=[(0, 'wgs84'), (1, 'amsl'), (2, 'agl'), (3, 'sps')], default=0),
        ),
        migrations.AddField(
            model_name='rpas',
            name='begin_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rpas',
            name='category',
            field=models.IntegerField(choices=[(0, 'Other'), (1, 'FIXED WING'), (2, 'ROTORCRAFT'), (3, 'LIGHTER-THAN-AIR'), (4, 'HYBRID LIFT')], default=0),
        ),
        migrations.AddField(
            model_name='rpas',
            name='icao_aircraft_type_designator',
            field=models.CharField(default='0000', max_length=4),
        ),
        migrations.AddField(
            model_name='rpas',
            name='make',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
        migrations.AddField(
            model_name='rpas',
            name='master_series',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
        migrations.AddField(
            model_name='rpas',
            name='max_certified_takeoff_weight',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rpas',
            name='popular_name',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
        migrations.AddField(
            model_name='rpas',
            name='series',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
        migrations.AddField(
            model_name='rpas',
            name='sub_category',
            field=models.IntegerField(choices=[(0, 'Other'), (1, 'AIRPLANE'), (2, 'NONPOWERED GLIDER'), (3, 'POWERED GLIDER'), (4, 'HELICOPTER'), (5, 'GYROPLANE'), (6, 'BALLOON'), (6, 'AIRSHIP'), (7, 'UAV')], default=7),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.IntegerField(choices=[(0, 'NA'), (1, 'Open'), (2, 'Specific')], default=0),
        ),
        migrations.AlterField(
            model_name='authorization',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 27, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rpas',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.Manufacturer'),
        ),
        migrations.AddField(
            model_name='rpas',
            name='type_certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.RpasTypeCertificate'),
        ),
    ]
