# Generated by Django 2.2 on 2019-04-25 09:02

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_auto_20190424_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='authorization',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 25, 0, 0, tzinfo=utc)),
        ),
    ]
