# Generated by Django 2.2 on 2019-04-25 11:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0009_auto_20190425_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 25, 0, 0, tzinfo=utc)),
        ),
    ]
