# Generated by Django 2.2.3 on 2019-07-10 11:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0010_operator_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='image_small',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='authorization',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 10, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_contact', to='registry.Operator'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 10, 0, 0, tzinfo=utc)),
        ),
    ]
