# Generated by Django 2.2.5 on 2019-10-24 16:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0013_auto_20190712_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pilot',
            old_name='identificationiphoto_small',
            new_name='identification_photo_small',
        ),
        migrations.AlterField(
            model_name='authorization',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 24, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='operator',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 24, 0, 0, tzinfo=utc)),
        ),
    ]
