# Generated by Django 3.1.3 on 2020-11-29 22:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0017_auto_20201128_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=15)),
                ('power', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('count', models.IntegerField(default=1)),
                ('engine_type', models.CharField(max_length=15)),
                ('propellor', models.CharField(max_length=140)),
            ],
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='operating_frequencies',
        ),
        migrations.AddField(
            model_name='aircraft',
            name='compatible_payload',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='dimension_breadth',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='dimension_height',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='dimension_length',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='fuel_capacity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='max_endurance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='max_height_attainable',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='max_range',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='max_speed',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='category',
            field=models.IntegerField(choices=[(0, 'Other'), (1, 'FIXED WING'), (2, 'ROTORCRAFT'), (3, 'LIGHTER-THAN-AIR'), (4, 'HYBRID LIFT'), (5, 'MICRO'), (6, 'SMALL'), (7, 'MEIDUM'), (8, 'Large')], default=0),
        ),
        migrations.AlterField(
            model_name='authorization',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 29, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='operator',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 29, 0, 0, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='engine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.engine'),
        ),
    ]
