# Generated by Django 3.1.3 on 2020-12-01 21:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0019_auto_20201130_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='manufactured_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='authorization',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='operator',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 0, 0, tzinfo=utc)),
        ),
    ]
