# Generated by Django 3.1.5 on 2021-01-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0025_auto_20210127_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(choices=[('IN', 'INDIA')], default='NA', max_length=2),
        ),
        migrations.AlterField(
            model_name='operator',
            name='country',
            field=models.CharField(choices=[('IN', 'INDIA')], default='NA', max_length=2),
        ),
    ]
