# Generated by Django 3.1.5 on 2021-01-28 10:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0026_auto_20210127_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='flight_controller_number',
            field=models.CharField(default=0, help_text='This is the Drone ID', max_length=140),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='maci_number',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='authorization',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 28, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='operator',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 28, 0, 0, tzinfo=utc)),
        ),
    ]
