# Generated by Django 3.1.6 on 2021-02-03 22:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0028_auto_20210202_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='controller_public_key',
            field=models.TextField(default=0, help_text='This is the public key of the RFM used to sign log files'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='flight_controller_number',
            field=models.CharField(default=0, help_text='This is the Drone ID from the RFM', max_length=140),
        ),
        migrations.AlterField(
            model_name='authorization',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 3, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='operator',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 3, 0, 0, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Firmware',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('binary_file_url', models.URLField()),
                ('public_key', models.TextField()),
                ('version', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.manufacturer')),
            ],
        ),
    ]
