# Generated by Django 3.1.6 on 2021-02-04 09:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0030_auto_20210203_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='commission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='authorization',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 4, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='role',
            field=models.CharField(default='NA', help_text='e.g. Reseller, distributor, OEM etc.', max_length=140),
        ),
        migrations.AlterField(
            model_name='operator',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 4, 0, 0, tzinfo=utc)),
        ),
    ]
