# Generated by Django 3.1.6 on 2021-02-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0032_auto_20210204_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='commission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
