# Generated by Django 3.1.6 on 2021-02-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0035_auto_20210208_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='dot_permission_document',
            field=models.URLField(blank=True, help_text='Purchased RPA has ETA from WPC Wing, DoT for operating in the de-licensed frequency band(s). Such approval shall be valid for a particular make and model', null=True),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='operataions_manual_document',
            field=models.URLField(blank=True, help_text='Operation Manual Document', null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='cin_document',
            field=models.URLField(blank=True, help_text='Certificate of Incorporation issued by ROC, MCA', null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='eta_document',
            field=models.URLField(blank=True, help_text='Equipment Type Approval (ETA) from WPC Wing', null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='gst_document',
            field=models.URLField(blank=True, help_text='GST certification document', null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='pan_card_document',
            field=models.URLField(blank=True, help_text='URL of Manufacturers PAN Card scan', null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='security_clearance_document',
            field=models.URLField(blank=True, help_text='Security Clearance from Ministry of Home Affairs', null=True),
        ),
    ]
