# Generated by Django 3.1.6 on 2021-02-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0037_auto_20210216_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilot',
            name='identification_photo',
            field=models.URLField(default='https://github.com/openskies-sh/aerobridge/blob/master/sample-data/id-card-sample.jpeg'),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='identification_photo_small',
            field=models.URLField(default='https://github.com/openskies-sh/aerobridge/blob/master/sample-data/id-card-sample.jpeg'),
        ),
    ]
