# Generated by Django 3.1.6 on 2021-02-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0039_auto_20210216_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='digital_sky_uin_number',
            field=models.CharField(default=0, help_text='Get a UIN number for this aircraft using the Digital Sky Portal', max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='digital_sky_id',
            field=models.CharField(default=0, help_text='Use the Digital Sky portal to create a Manufacturer profile and get an ID, paste it here', max_length=140),
            preserve_default=False,
        ),
    ]
