# Generated by Django 3.2 on 2021-05-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0040_auto_20210216_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmware',
            name='binary_file_url',
            field=models.URLField(help_text='Enter a url from where the firmware can be downloaded'),
        ),
        migrations.AlterField(
            model_name='firmware',
            name='public_key',
            field=models.TextField(help_text='Enter a SHA / Digest or public key to test used to secure the firmware'),
        ),
    ]
