# Generated by Django 3.2.3 on 2021-05-19 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0044_auto_20210518_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engine',
            name='type',
        ),
    ]
