# Generated by Django 3.2.3 on 2021-05-19 14:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0045_remove_engine_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engine',
            name='engine_type',
            field=models.CharField(help_text='Specify the type of engine', max_length=15),
        ),
        migrations.AlterField(
            model_name='engine',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='engine',
            name='propellor',
            field=models.CharField(help_text='Specify number of propellors', max_length=140),
        ),
    ]
