# Generated by Django 3.2.3 on 2021-05-26 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registry', '0045_remove_engine_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engine',
            name='engine_type',
            field=models.CharField(help_text='Specify the type of engine', max_length=15),
        ),
        migrations.AlterField(
            model_name='engine',
            name='propellor',
            field=models.CharField(help_text='Specify number of propellors', max_length=140),
        ),
        migrations.CreateModel(
            name='HistoricalAircraft',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('mass', models.IntegerField()),
                ('is_airworthy', models.BooleanField(default=0)),
                ('make', models.CharField(blank=True, max_length=280, null=True)),
                ('master_series', models.CharField(blank=True, max_length=280, null=True)),
                ('series', models.CharField(blank=True, max_length=280, null=True)),
                ('popular_name', models.CharField(blank=True, max_length=280, null=True)),
                ('category', models.IntegerField(choices=[(0, 'Other'), (1, 'FIXED WING'), (2, 'ROTORCRAFT'), (3, 'LIGHTER-THAN-AIR'), (4, 'HYBRID LIFT'), (5, 'MICRO'), (6, 'SMALL'), (7, 'MEIDUM'), (8, 'Large')], default=0)),
                ('registration_mark', models.CharField(blank=True, max_length=10, null=True)),
                ('sub_category', models.IntegerField(choices=[(0, 'Other'), (1, 'AIRPLANE'), (2, 'NONPOWERED GLIDER'), (3, 'POWERED GLIDER'), (4, 'HELICOPTER'), (5, 'GYROPLANE'), (6, 'BALLOON'), (6, 'AIRSHIP'), (7, 'UAV'), (8, 'Multirotor'), (9, 'Hybrid')], default=7)),
                ('icao_aircraft_type_designator', models.CharField(default='0000', max_length=4)),
                ('max_certified_takeoff_weight', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('max_height_attainable', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('compatible_payload', models.CharField(blank=True, max_length=20, null=True)),
                ('commission_date', models.DateTimeField(blank=True, null=True)),
                ('model', models.CharField(max_length=280)),
                ('esn', models.CharField(default='000000000000000000000000000000000000000000000000', max_length=48)),
                ('digital_sky_uin_number', models.CharField(help_text='Get a UIN number for this aircraft using the Digital Sky Portal', max_length=140)),
                ('maci_number', models.CharField(max_length=200)),
                ('flight_controller_number', models.CharField(default=0, help_text='This is the Drone ID from the RFM', max_length=140)),
                ('controller_public_key', models.TextField(default=0, help_text='This is the public key of the RFM used to sign log files')),
                ('operating_frequency', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('photo', models.URLField(blank=True, null=True)),
                ('photo_small', models.URLField(blank=True, null=True)),
                ('identification_photo', models.URLField(blank=True, null=True)),
                ('identification_photo_small', models.URLField(blank=True, null=True)),
                ('is_registered', models.BooleanField(default=False)),
                ('fuel_capacity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('max_endurance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('max_range', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('max_speed', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('dimension_length', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('dimension_breadth', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('dimension_height', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('manufactured_at', models.DateTimeField(null=True)),
                ('dot_permission_document', models.URLField(default='https://raw.githubusercontent.com/openskies-sh/aerobridge/master/sample-data/Aerobridge-placeholder-document.pdf', help_text='Link to Purchased RPA has ETA from WPC Wing, DoT for operating in the de-licensed frequency band(s). Such approval shall be valid for a particular make and model')),
                ('operataions_manual_document', models.URLField(default='https://raw.githubusercontent.com/openskies-sh/aerobridge/master/sample-data/Aerobridge-placeholder-document.pdf', help_text='Link to Operation Manual Document')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('engine', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.engine')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('manufacturer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.manufacturer')),
                ('operator', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.operator')),
                ('type_certificate', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.typecertificate')),
            ],
            options={
                'verbose_name': 'historical aircraft',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
