# Generated by Django 3.2.4 on 2021-06-17 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0048_auto_20210611_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='address',
            field=models.ForeignKey(help_text='Select the official address for the company', on_delete=django.db.models.deletion.CASCADE, to='registry.address'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='authorized_activities',
            field=models.ManyToManyField(help_text='Related to Authorization, select the kind of activities that this operator is allowed to conduct, you can add additional activities using the administration panel', related_name='authorized_activities', to='registry.Activity'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='company_name',
            field=models.CharField(help_text='Official Name of the company as in the Company Registration Office', max_length=28),
        ),
        migrations.AlterField(
            model_name='operator',
            name='company_number',
            field=models.CharField(default='CO-TMP', max_length=25),
        ),
        migrations.AlterField(
            model_name='operator',
            name='country',
            field=models.CharField(choices=[('IN', 'INDIA')], default='IN', max_length=2),
        ),
        migrations.AlterField(
            model_name='operator',
            name='email',
            field=models.EmailField(help_text='Contact email for support and other queries', max_length=254),
        ),
        migrations.AlterField(
            model_name='operator',
            name='insurance_number',
            field=models.CharField(default='INS-TMP', max_length=25),
        ),
        migrations.AlterField(
            model_name='operator',
            name='operational_authorizations',
            field=models.ManyToManyField(help_text='Choose what kind of authorization this operator posseses, to add additional authorizations, use the administration panel', related_name='operational_authorizations', to='registry.Authorization'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='operator_type',
            field=models.IntegerField(choices=[(0, 'NA'), (1, 'LUC'), (2, 'Non-LUC'), (3, 'AUTH'), (4, 'DEC')], default=0, help_text='Choose what kind of operator this is, classify the operator based on capabilites, use the adminsitration panel to add additional operator categories'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='vat_number',
            field=models.CharField(default='VAT-TMP', max_length=25),
        ),
        migrations.AlterField(
            model_name='operator',
            name='website',
            field=models.URLField(help_text='Put official URL'),
        ),
    ]
