# Generated by Django 3.2.4 on 2021-06-21 12:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0049_auto_20210617_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='company_name',
            field=models.CharField(help_text='Official Name of the company as in the Company Registration Office', max_length=28, validators=[django.core.validators.RegexValidator(message='No special characters allowed in this field. Special characters are for e.g. !@#$%^&* ', regex='\\W')]),
        ),
        migrations.AlterField(
            model_name='operator',
            name='company_number',
            field=models.CharField(default='CO-TMP', max_length=25, validators=[django.core.validators.RegexValidator(message='No special characters allowed in this field. Special characters are for e.g. !@#$%^&* ', regex='\\W')]),
        ),
        migrations.AlterField(
            model_name='operator',
            name='insurance_number',
            field=models.CharField(default='INS-TMP', max_length=25, validators=[django.core.validators.RegexValidator(message='No special characters allowed in this field. Special characters are for e.g. !@#$%^&* ', regex='\\W')]),
        ),
        migrations.AlterField(
            model_name='operator',
            name='vat_number',
            field=models.CharField(default='VAT-TMP', max_length=25, validators=[django.core.validators.RegexValidator(message='No special characters allowed in this field. Special characters are for e.g. !@#$%^&* ', regex='\\W')]),
        ),
        migrations.AlterField(
            model_name='operator',
            name='website',
            field=models.URLField(help_text='Put official URL', validators=[django.core.validators.RegexValidator(message='No special characters allowed in this field. Special characters are for e.g. !@#$%^&* ', regex='\\W')]),
        ),
    ]
