# Generated by Django 3.2.7 on 2021-09-24 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0051_auto_20210623_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircraft',
            name='controller_public_key',
        ),
        migrations.RemoveField(
            model_name='historicalaircraft',
            name='controller_public_key',
        ),
    ]
