# Generated by Django 3.2.7 on 2021-09-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0052_auto_20210924_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircraft',
            name='fuel_capacity',
        ),
        migrations.RemoveField(
            model_name='historicalaircraft',
            name='fuel_capacity',
        ),
        migrations.AlterField(
            model_name='engine',
            name='power',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Specify the engine power', max_digits=10),
        ),
    ]
