# Generated by Django 3.2.7 on 2021-09-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0053_auto_20210924_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engine',
            name='propellor',
            field=models.IntegerField(help_text='Specify number of propellors'),
        ),
    ]
