# Generated by Django 3.2.7 on 2021-09-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0054_alter_engine_propellor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='sub_category',
            field=models.IntegerField(choices=[(0, 'Other'), (1, 'AIRPLANE'), (2, 'NONPOWERED GLIDER'), (3, 'POWERED GLIDER'), (4, 'HELICOPTER'), (5, 'GYROPLANE'), (6, 'BALLOON'), (7, 'AIRSHIP'), (8, 'UAV'), (9, 'Multirotor'), (10, 'Hybrid')], default=7),
        ),
        migrations.AlterField(
            model_name='historicalaircraft',
            name='sub_category',
            field=models.IntegerField(choices=[(0, 'Other'), (1, 'AIRPLANE'), (2, 'NONPOWERED GLIDER'), (3, 'POWERED GLIDER'), (4, 'HELICOPTER'), (5, 'GYROPLANE'), (6, 'BALLOON'), (7, 'AIRSHIP'), (8, 'UAV'), (9, 'Multirotor'), (10, 'Hybrid')], default=7),
        ),
    ]
