# Generated by Django 3.2.7 on 2021-10-04 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0055_auto_20210927_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aircraft',
            old_name='flight_controller_number',
            new_name='flight_controller_id',
        ),
        migrations.RenameField(
            model_name='historicalaircraft',
            old_name='flight_controller_number',
            new_name='flight_controller_id',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='compatible_payload',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='esn',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='is_airworthy',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='maci_number',
        ),
        migrations.RemoveField(
            model_name='historicalaircraft',
            name='compatible_payload',
        ),
        migrations.RemoveField(
            model_name='historicalaircraft',
            name='esn',
        ),
        migrations.RemoveField(
            model_name='historicalaircraft',
            name='is_airworthy',
        ),
        migrations.RemoveField(
            model_name='historicalaircraft',
            name='maci_number',
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='category',
            field=models.IntegerField(choices=[(0, 'Other'), (1, 'FIXED WING'), (2, 'ROTORCRAFT'), (3, 'LIGHTER-THAN-AIR'), (4, 'HYBRID LIFT'), (5, 'MICRO'), (6, 'SMALL'), (7, 'MEIDUM'), (8, 'Large')], default=0, help_text='Set the category for this aircraft'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='dimension_breadth',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Set the breadth of the drone in cms', max_digits=10),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='dimension_height',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Set the height of the drone in cms', max_digits=10),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='dimension_length',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Set the length of the drone in cms', max_digits=10),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='engine',
            field=models.ForeignKey(blank=True, help_text='Associate a engine with this aircraft', null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.engine'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='icao_aircraft_type_designator',
            field=models.CharField(default='0000', help_text='If available you can specify the type designator, see https://www.icao.int/publications/doc8643/pages/search.aspx', max_length=4),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='identification_photo',
            field=models.URLField(blank=True, help_text='A link to a photo of the URL', null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='identification_photo_small',
            field=models.URLField(blank=True, help_text='A link to a photo of the URL', null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='is_registered',
            field=models.BooleanField(default=False, help_text='Set if the aircraft is registred with the Civil Aviation Authority'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='manufactured_at',
            field=models.DateTimeField(help_text='Set the date when the drone was manufactureed', null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='manufacturer',
            field=models.ForeignKey(help_text='Associate a manufacturer to this aircraft', on_delete=django.db.models.deletion.CASCADE, to='registry.manufacturer'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='mass',
            field=models.IntegerField(default=300, help_text='Set a mass in gms.'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='max_certified_takeoff_weight',
            field=models.DecimalField(decimal_places=3, default=0.0, help_text='Set the takeoff weight for the aircraft in gms.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='max_endurance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Set the endurance in minutes', max_digits=10),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='max_height_attainable',
            field=models.DecimalField(decimal_places=3, default=0.0, help_text='Set the max attainable height in meters', max_digits=10),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='max_range',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Set the range in kms for the drone', max_digits=10),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='max_speed',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Set the maximum speed in km/hr.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='model',
            field=models.CharField(help_text='Set the model of the aircraft', max_length=280),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='operator',
            field=models.ForeignKey(help_text='Associate a operator to this Aircraft', on_delete=django.db.models.deletion.CASCADE, to='registry.operator'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='photo',
            field=models.URLField(blank=True, help_text='A link to a photo of the URL', null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='photo_small',
            field=models.URLField(blank=True, help_text='A link to a photo of the URL', null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='registration_mark',
            field=models.CharField(blank=True, help_text='Set the registration mark for this aircraft', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='type_certificate',
            field=models.ForeignKey(blank=True, help_text='Set the type certificate if available for the drone', null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.typecertificate'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='count',
            field=models.IntegerField(default=1, help_text='Set the number of engines normally present'),
        ),
        migrations.AlterField(
            model_name='firmware',
            name='manufacturer',
            field=models.ForeignKey(help_text='Associate a manufacturer to the firmware', on_delete=django.db.models.deletion.CASCADE, to='registry.manufacturer'),
        ),
        migrations.AlterField(
            model_name='firmware',
            name='version',
            field=models.CharField(help_text='Set a semantic version for the firmware version', max_length=25),
        ),
        migrations.AlterField(
            model_name='historicalaircraft',
            name='category',
            field=models.IntegerField(choices=[(0, 'Other'), (1, 'FIXED WING'), (2, 'ROTORCRAFT'), (3, 'LIGHTER-THAN-AIR'), (4, 'HYBRID LIFT'), (5, 'MICRO'), (6, 'SMALL'), (7, 'MEIDUM'), (8, 'Large')], default=0, help_text='Set the category for this aircraft'),
        ),
        migrations.AlterField(
            model_name='historicalaircraft',
            name='dimension_breadth',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Set the breadth of the drone in cms', max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicalaircraft',
            name='dimension_height',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Set the height of the drone in cms', max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicalaircraft',
            name='dimension_length',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Set the length of the drone in cms', max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicalaircraft',
            name='engine',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Associate a engine with this aircraft', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.engine'),
        ),
        migrations.AlterField(
            model_name='historicalaircraft',
            name='icao_aircraft_type_designator',
            field=models.CharField(default='0000', help_text='If available you can specify the type designator, see https://www.icao.int/publications/doc8643/pages/search.aspx', max_length=4),
        ),
        migrations.AlterField(
            model_name='historicalaircraft',
            name='identification_photo',
            field=models.URLField(blank=True, help_text='A link to a photo of the URL', null=True),
        ),
        migrations.AlterField(
            model_name='historicalaircraft',
            name='identification_photo_small',
            field=models.URLField(blank=True, help_text='A link to a photo of the URL', null=True),
        ),
        migrations.AlterField(
            model_name='historicalaircraft',
            name='is_registered',
            field=models.BooleanField(default=False, help_text='Set if the aircraft is registred with the Civil Aviation Authority'),
        ),
        migrations.AlterField(
            model_name='historicalaircraft',
            name='manufactured_at',
            field=models.DateTimeField(help_text='Set the date when the drone was manufactureed', null=True),
        ),
        migrations.AlterField(
            model_name='historicalaircraft',
            name='manufacturer',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Associate a manufacturer to this aircraft', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.manufacturer'),
        ),
        migrations.AlterField(
            model_name='historicalaircraft',
            name='mass',
            field=models.IntegerField(default=300, help_text='Set a mass in gms.'),
        ),
        migrations.AlterField(
            model_name='historicalaircraft',
            name='max_certified_takeoff_weight',
            field=models.DecimalField(decimal_places=3, default=0.0, help_text='Set the takeoff weight for the aircraft in gms.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicalaircraft',
            name='max_endurance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Set the endurance in minutes', max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicalaircraft',
            name='max_height_attainable',
            field=models.DecimalField(decimal_places=3, default=0.0, help_text='Set the max attainable height in meters', max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicalaircraft',
            name='max_range',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Set the range in kms for the drone', max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicalaircraft',
            name='max_speed',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Set the maximum speed in km/hr.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicalaircraft',
            name='model',
            field=models.CharField(help_text='Set the model of the aircraft', max_length=280),
        ),
        migrations.AlterField(
            model_name='historicalaircraft',
            name='operator',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Associate a operator to this Aircraft', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.operator'),
        ),
        migrations.AlterField(
            model_name='historicalaircraft',
            name='photo',
            field=models.URLField(blank=True, help_text='A link to a photo of the URL', null=True),
        ),
        migrations.AlterField(
            model_name='historicalaircraft',
            name='photo_small',
            field=models.URLField(blank=True, help_text='A link to a photo of the URL', null=True),
        ),
        migrations.AlterField(
            model_name='historicalaircraft',
            name='registration_mark',
            field=models.CharField(blank=True, help_text='Set the registration mark for this aircraft', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalaircraft',
            name='type_certificate',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Set the type certificate if available for the drone', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.typecertificate'),
        ),
    ]
