# Generated by Django 3.2.7 on 2021-10-04 16:40

from django.db import migrations, models
import registry.models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0056_auto_20211004_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='flight_controller_id',
            field=models.CharField(default=0, help_text='This is the Drone ID from the RFM', max_length=140, validators=[registry.models.validate_flight_controller_id]),
        ),
        migrations.AlterField(
            model_name='historicalaircraft',
            name='flight_controller_id',
            field=models.CharField(default=0, help_text='This is the Drone ID from the RFM', max_length=140, validators=[registry.models.validate_flight_controller_id]),
        ),
    ]
