# Generated by Django 3.2.7 on 2021-10-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0057_auto_20211004_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='digital_sky_uin_number',
            field=models.CharField(blank=True, help_text='Get a UIN number for this aircraft using the Digital Sky Portal', max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='manufactured_at',
            field=models.DateTimeField(blank=True, help_text='Set the date when the drone was manufactured', null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='mass',
            field=models.IntegerField(default=300, help_text="Set the vehicle's mass in gms."),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='operating_frequency',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalaircraft',
            name='digital_sky_uin_number',
            field=models.CharField(blank=True, help_text='Get a UIN number for this aircraft using the Digital Sky Portal', max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='historicalaircraft',
            name='manufactured_at',
            field=models.DateTimeField(blank=True, help_text='Set the date when the drone was manufactured', null=True),
        ),
        migrations.AlterField(
            model_name='historicalaircraft',
            name='mass',
            field=models.IntegerField(default=300, help_text="Set the vehicle's mass in gms."),
        ),
        migrations.AlterField(
            model_name='historicalaircraft',
            name='operating_frequency',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
