# Generated by Django 3.2.7 on 2021-10-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0058_auto_20211004_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='icao_aircraft_type_designator',
            field=models.CharField(blank=True, default='0000', help_text='If available you can specify the type designator, see https://www.icao.int/publications/doc8643/pages/search.aspx', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='historicalaircraft',
            name='icao_aircraft_type_designator',
            field=models.CharField(blank=True, default='0000', help_text='If available you can specify the type designator, see https://www.icao.int/publications/doc8643/pages/search.aspx', max_length=4, null=True),
        ),
    ]
