# Generated by Django 3.2.7 on 2021-10-05 12:23

from django.db import migrations, models
import registry.models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0060_auto_20211004_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='dot_permission_document',
            field=models.URLField(blank=True, default='https://raw.githubusercontent.com/openskies-sh/aerobridge/master/sample-data/Aerobridge-placeholder-document.pdf', help_text='Link to Purchased RPA has ETA from WPC Wing, DoT for operating in the de-licensed frequency band(s). Such approval shall be valid for a particular make and model', null=True, validators=[registry.models.validate_url]),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='operataions_manual_document',
            field=models.URLField(blank=True, default='https://raw.githubusercontent.com/openskies-sh/aerobridge/master/sample-data/Aerobridge-placeholder-document.pdf', help_text='Link to Operation Manual Document', null=True, validators=[registry.models.validate_url]),
        ),
        migrations.AlterField(
            model_name='historicalaircraft',
            name='dot_permission_document',
            field=models.URLField(blank=True, default='https://raw.githubusercontent.com/openskies-sh/aerobridge/master/sample-data/Aerobridge-placeholder-document.pdf', help_text='Link to Purchased RPA has ETA from WPC Wing, DoT for operating in the de-licensed frequency band(s). Such approval shall be valid for a particular make and model', null=True, validators=[registry.models.validate_url]),
        ),
        migrations.AlterField(
            model_name='historicalaircraft',
            name='operataions_manual_document',
            field=models.URLField(blank=True, default='https://raw.githubusercontent.com/openskies-sh/aerobridge/master/sample-data/Aerobridge-placeholder-document.pdf', help_text='Link to Operation Manual Document', null=True, validators=[registry.models.validate_url]),
        ),
    ]
