# Generated by Django 3.2.7 on 2021-10-05 13:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import registry.models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0061_auto_20211005_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='identification_number',
        ),
        migrations.AddField(
            model_name='person',
            name='identification_document',
            field=models.URLField(blank=True, default='https://raw.githubusercontent.com/openskies-sh/aerobridge/master/sample-data/Aerobridge-placeholder-document.pdf', max_length=280, null=True, validators=[registry.models.validate_url]),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='category',
            field=models.IntegerField(choices=[(0, 'Other'), (1, 'FIXED WING'), (2, 'ROTORCRAFT'), (3, 'LIGHTER-THAN-AIR'), (4, 'HYBRID LIFT'), (5, 'MICRO'), (6, 'SMALL'), (7, 'MEIDUM'), (8, 'Large')], default=0, help_text='Set the category for this aircraft, use the closest aircraft type'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='flight_controller_id',
            field=models.CharField(default=0, help_text='This is the Drone ID from the RFM, if there are spaces in the ID, remove them', max_length=140, validators=[registry.models.validate_flight_controller_id]),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='identification_photo',
            field=models.URLField(blank=True, help_text='A URL to a photo of the drone ID or other identifying image of the drone.', null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='identification_photo_small',
            field=models.URLField(blank=True, help_text='A cropped version of the', null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='manufacturer',
            field=models.ForeignKey(help_text='Associate a manufacturer in the database to this aircraft', on_delete=django.db.models.deletion.CASCADE, to='registry.manufacturer'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='master_series',
            field=models.CharField(blank=True, help_text='Specify the master series, if available', max_length=280, null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='photo',
            field=models.URLField(default='https://raw.githubusercontent.com/openskies-sh/aerobridge/master/sample-data/Aerobridge-placeholder-document.pdf', help_text='A URL of a photo of the drone'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='photo_small',
            field=models.URLField(default='https://raw.githubusercontent.com/openskies-sh/aerobridge/master/sample-data/Aerobridge-placeholder-document.pdf', help_text='A URL of a small photo of the drone, used in the list page on the server'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='registration_mark',
            field=models.CharField(blank=True, help_text='Set the registration mark for this aircraft, if applicable', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='series',
            field=models.CharField(blank=True, help_text='Enter aircraft production series, if available', max_length=280, null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, help_text='Set the status of this drone, if it is set as inactive, the GCS might fail and flight plans might not be able to load on the drone'),
        ),
        migrations.AlterField(
            model_name='historicalaircraft',
            name='category',
            field=models.IntegerField(choices=[(0, 'Other'), (1, 'FIXED WING'), (2, 'ROTORCRAFT'), (3, 'LIGHTER-THAN-AIR'), (4, 'HYBRID LIFT'), (5, 'MICRO'), (6, 'SMALL'), (7, 'MEIDUM'), (8, 'Large')], default=0, help_text='Set the category for this aircraft, use the closest aircraft type'),
        ),
        migrations.AlterField(
            model_name='historicalaircraft',
            name='flight_controller_id',
            field=models.CharField(default=0, help_text='This is the Drone ID from the RFM, if there are spaces in the ID, remove them', max_length=140, validators=[registry.models.validate_flight_controller_id]),
        ),
        migrations.AlterField(
            model_name='historicalaircraft',
            name='identification_photo',
            field=models.URLField(blank=True, help_text='A URL to a photo of the drone ID or other identifying image of the drone.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalaircraft',
            name='identification_photo_small',
            field=models.URLField(blank=True, help_text='A cropped version of the', null=True),
        ),
        migrations.AlterField(
            model_name='historicalaircraft',
            name='manufacturer',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Associate a manufacturer in the database to this aircraft', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.manufacturer'),
        ),
        migrations.AlterField(
            model_name='historicalaircraft',
            name='master_series',
            field=models.CharField(blank=True, help_text='Specify the master series, if available', max_length=280, null=True),
        ),
        migrations.AlterField(
            model_name='historicalaircraft',
            name='photo',
            field=models.URLField(default='https://raw.githubusercontent.com/openskies-sh/aerobridge/master/sample-data/Aerobridge-placeholder-document.pdf', help_text='A URL of a photo of the drone'),
        ),
        migrations.AlterField(
            model_name='historicalaircraft',
            name='photo_small',
            field=models.URLField(default='https://raw.githubusercontent.com/openskies-sh/aerobridge/master/sample-data/Aerobridge-placeholder-document.pdf', help_text='A URL of a small photo of the drone, used in the list page on the server'),
        ),
        migrations.AlterField(
            model_name='historicalaircraft',
            name='registration_mark',
            field=models.CharField(blank=True, help_text='Set the registration mark for this aircraft, if applicable', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalaircraft',
            name='series',
            field=models.CharField(blank=True, help_text='Enter aircraft production series, if available', max_length=280, null=True),
        ),
        migrations.AlterField(
            model_name='historicalaircraft',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, help_text='Set the status of this drone, if it is set as inactive, the GCS might fail and flight plans might not be able to load on the drone'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(help_text='The first name of the person added to the database', max_length=30),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
