# Generated by Django 3.2.7 on 2021-10-05 13:21

from django.db import migrations, models
import registry.models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0063_auto_20211005_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='identification_document',
            field=models.URLField(blank=True, default='https://raw.githubusercontent.com/openskies-sh/aerobridge/master/sample-data/Aerobridge-placeholder-document.pdf', null=True, validators=[registry.models.validate_url]),
        ),
    ]
