# Generated by Django 3.2.8 on 2021-10-08 16:21

from django.db import migrations, models
import registry.models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0066_auto_20211008_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aircraft',
            old_name='operataions_manual_document',
            new_name='operations_manual_document',
        ),
        migrations.RenameField(
            model_name='historicalaircraft',
            old_name='operataions_manual_document',
            new_name='operations_manual_document',
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='flight_controller_id',
            field=models.CharField(help_text='This is the Drone ID from the RFM, if there are spaces in the ID, remove them', max_length=140, validators=[registry.models.validate_flight_controller_id]),
        ),
        migrations.AlterField(
            model_name='historicalaircraft',
            name='flight_controller_id',
            field=models.CharField(help_text='This is the Drone ID from the RFM, if there are spaces in the ID, remove them', max_length=140, validators=[registry.models.validate_flight_controller_id]),
        ),
        migrations.AlterField(
            model_name='operator',
            name='website',
            field=models.URLField(help_text='Put official URL of the company, if none is avaiable then a manufacturers'),
        ),
    ]
