# Generated by Django 3.2.7 on 2021-10-09 20:53

from django.db import migrations, models
import django.db.models.deletion
import registry.models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0067_auto_20211008_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.ForeignKey(help_text='Add a address for this contact', on_delete=django.db.models.deletion.CASCADE, to='registry.address'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='operator',
            field=models.ForeignKey(help_text='Set a operator for this contact', on_delete=django.db.models.deletion.CASCADE, related_name='person_contact', to='registry.operator'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='person',
            field=models.ForeignKey(help_text='Associate a person for this contact', on_delete=django.db.models.deletion.CASCADE, to='registry.person'),
        ),
        migrations.AlterField(
            model_name='firmware',
            name='is_active',
            field=models.BooleanField(default=False, help_text="Set if the firmware is active, don't forget to mark old firmware as inactive"),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='photo',
            field=models.URLField(blank=True, help_text='A URL to link to a photo of the pilot', null=True, validators=[registry.models.validate_url]),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='photo_small',
            field=models.URLField(blank=True, help_text='A URL to link to a photo (small) of the pilot', null=True, validators=[registry.models.validate_url]),
        ),
    ]
