# Generated by Django 3.1.3 on 2020-11-24 16:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gcs_operations', '0003_auto_20201124_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalSkyLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('response_code', models.CharField(max_length=256)),
                ('timestamp', models.DateTimeField()),
                ('txn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcs_operations.transaction')),
            ],
        ),
    ]
