# Generated by Django 3.1.3 on 2020-11-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalsky_provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalskylog',
            name='response',
            field=models.TextField(default='Response from DGCA Server stored here'),
        ),
    ]
