# Generated by Django 3.1.4 on 2020-12-04 19:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0021_auto_20201204_1908'),
        ('digitalsky_provider', '0002_digitalskylog_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalskylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='digitalskylog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='AircraftRegister',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_signed', models.BooleanField(default=False)),
                ('signature', models.TextField()),
                ('certificate', models.TextField()),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.aircraft')),
            ],
        ),
    ]
