# Generated by Django 3.1.6 on 2021-02-07 22:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('digitalsky_provider', '0003_auto_20201204_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraftregister',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aircraftregister',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
