# Generated by Django 3.1.6 on 2021-02-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalsky_provider', '0004_auto_20210207_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraftregister',
            name='certificate',
            field=models.TextField(help_text='Your Public Key will go here, this will be submitted to Digital Sky when registering a drone'),
        ),
        migrations.AlterField(
            model_name='aircraftregister',
            name='signature',
            field=models.TextField(help_text='Use a DSC to sign the json above and paste the signed document here.'),
        ),
    ]
