# Generated by Django 3.2.1 on 2021-05-06 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitalsky_provider', '0005_auto_20210208_1514'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AircraftRegister',
        ),
    ]
