# Generated by Django 3.2.4 on 2021-06-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalsky_provider', '0006_delete_aircraftregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalskylog',
            name='response',
            field=models.TextField(default='Raw response from DGCA Digital Sky Server is stored here.'),
        ),
    ]
