# Generated by Django 4.1.7 on 2023-04-12 16:39

import common.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AerobridgeExternalCredential',
            fields=[
                ('token_type', models.IntegerField(choices=[(0, 'Full Chain')], help_text='Set the type of credential this is, e.g Public / Private Key etc.')),
                ('association', models.IntegerField(choices=[(0, 'Auth Server')], default=4, help_text='Set the entity this credential is associated with. The association will be used when calling external servers.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('binary_file_url', models.URLField(help_text='Enter a url from where the credential can be downloaded', validators=[common.validators.validate_url])),
                ('name', models.CharField(help_text='Give it a friendly name e.g. Auth server full chain pem', max_length=140)),
                ('is_active', models.BooleanField(default=False, help_text="Set if the credential is active, don't forget to mark old credentials as inactive")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AerobridgeCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Provide a friendly name / description for the type of credential you are storing e.g. eBee Public Key', max_length=100, validators=[django.core.validators.RegexValidator(message='No special characters allowed in this field.', regex='^[-, ,_\\w]*$')])),
                ('token_type', models.IntegerField(choices=[(0, 'Public Key'), (1, 'x509 Digital Certificate')], help_text='Set the type of credential this is, e.g Public / Private Key etc.')),
                ('association', models.IntegerField(choices=[(0, 'Operator'), (1, 'Manufacturer'), (2, 'Pilot'), (3, 'RFM'), (4, 'Company'), (5, 'Management Server')], default=4, help_text='Set the entity this credential is associated with. The association will be used when calling external servers.')),
                ('token', models.BinaryField()),
                ('extension', models.IntegerField(choices=[(0, 'other'), (1, '.jwk')], default=0, help_text='Specify the data format for this credential, if known')),
                ('is_active', models.BooleanField(default=True, help_text='Set whether the credential is still active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.aircraft')),
                ('manufacturer', models.ForeignKey(blank=True, limit_choices_to={'role': 1}, null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.company')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.operator')),
            ],
        ),
    ]
