# Generated by Django 3.2.8 on 2021-10-12 12:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AerobridgeCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter a friendly name / description for the type of credential you are storing', max_length=100, validators=[django.core.validators.RegexValidator(message='No special characters allowed in this field.', regex='^[-, ,_\\w]*$')])),
                ('token_type', models.IntegerField(choices=[(0, 'PUBLIC_KEY'), (1, 'PRIVATE_KEY'), (2, 'AUTHENTICATION TOKEN'), (3, 'OTHER'), (4, 'x509 DIGITAL CERTIFICATE')], help_text='Set the type of credential this is, e.g Public / Private Key')),
                ('association', models.IntegerField(choices=[(0, 'OPERATOR'), (1, 'MANUFACTURER'), (2, 'PILOT'), (3, 'RFM'), (4, 'Company')], default=4, help_text='Set the entity this credential is associated with. The association will be used when calling external servers.')),
                ('token', models.BinaryField()),
                ('is_active', models.BooleanField(default=True, help_text='Set whether the credential is still active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.aircraft')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.manufacturer')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.operator')),
            ],
        ),
    ]
