# Generated by Django 3.2.8 on 2021-10-31 21:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pki_framework', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aerobridgecredential',
            name='extension',
            field=models.IntegerField(choices=[(0, 'other'), (1, '.der'), (2, '.csr'), (3, '.key'), (4, '.cer'), (5, '.pem')], default=0, help_text='Specify the data format for this data, if known'),
        ),
        migrations.AlterField(
            model_name='aerobridgecredential',
            name='association',
            field=models.IntegerField(choices=[(0, 'Operator'), (1, 'Manufacturer'), (2, 'Pilot'), (3, 'RFM'), (4, 'Company'), (5, 'Management Server')], default=4, help_text='Set the entity this credential is associated with. The association will be used when calling external servers.'),
        ),
        migrations.AlterField(
            model_name='aerobridgecredential',
            name='name',
            field=models.CharField(help_text='Provide a friendly name / description for the type of credential you are storing e.g. eBee Public Key', max_length=100, validators=[django.core.validators.RegexValidator(message='No special characters allowed in this field.', regex='^[-, ,_\\w]*$')]),
        ),
        migrations.AlterField(
            model_name='aerobridgecredential',
            name='token_type',
            field=models.IntegerField(choices=[(0, 'Public Key'), (1, 'Private Key'), (2, 'Authentication Token'), (3, 'Other'), (4, 'x509 Digital Certificate')], help_text='Set the type of credential this is, e.g Public / Private Key etc.'),
        ),
    ]
