# Generated by Django 3.1.7 on 2021-04-24 20:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pki_framework', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalskycredentials',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='digitalskycredentials',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='digitalskycredentials',
            name='token_type',
            field=models.IntegerField(choices=[(0, 'DIGITAL SKY OPERATOR'), (1, 'DIGITAL SKY MANUFACTURER'), (2, 'DIGITAL SKY PILOT'), (3, 'RFM')]),
        ),
    ]
