# Generated by Django 3.2.9 on 2021-11-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pki_framework', '0002_auto_20211031_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aerobridgecredential',
            name='extension',
            field=models.IntegerField(choices=[(0, 'other'), (1, '.der'), (2, '.csr'), (3, '.key'), (4, '.cer'), (5, '.pem')], default=0, help_text='Specify the data format for this credential, if known'),
        ),
        migrations.AlterField(
            model_name='aerobridgecredential',
            name='token_type',
            field=models.IntegerField(choices=[(0, 'Public Key'), (2, 'Authentication Token'), (3, 'Other'), (4, 'x509 Digital Certificate')], help_text='Set the type of credential this is, e.g Public / Private Key etc.'),
        ),
    ]
