# Generated by Django 3.1.7 on 2021-04-30 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pki_framework', '0002_auto_20210424_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalskycredentials',
            name='environment',
            field=models.IntegerField(choices=[(0, 'DIGITAL SKY OPERATOR'), (1, 'DIGITAL SKY MANUFACTURER'), (2, 'DIGITAL SKY PILOT'), (3, 'RFM'), (4, 'RFM')], default=4),
        ),
        migrations.AlterField(
            model_name='digitalskycredentials',
            name='token_type',
            field=models.IntegerField(choices=[(0, 'PUBLIC_KEY'), (1, 'PRIVATE_KEY'), (2, 'AUTHENTICATION TOKEN'), (3, 'RFM KEY'), (4, 'OTHER')]),
        ),
    ]
