# Generated by Django 3.2.1 on 2021-05-06 12:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pki_framework', '0003_auto_20210430_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='AerobridgeCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('token_type', models.IntegerField(choices=[(0, 'PUBLIC_KEY'), (1, 'PRIVATE_KEY'), (2, 'AUTHENTICATION TOKEN'), (4, 'OTHER')])),
                ('environment', models.IntegerField(choices=[(0, 'DIGITAL SKY OPERATOR'), (1, 'DIGITAL SKY MANUFACTURER'), (2, 'DIGITAL SKY PILOT'), (3, 'RFM'), (3, 'DSC / eMudra Token')], default=4)),
                ('token', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DigitalSkyCredentials',
        ),
    ]
