# Generated by Django 3.1.7 on 2021-05-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pki_framework', '0004_auto_20210506_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aerobridgecredential',
            old_name='environment',
            new_name='association',
        ),
        migrations.AddField(
            model_name='aerobridgecredential',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='aerobridgecredential',
            name='name',
            field=models.CharField(help_text='Enter a description for the type of credential you are storing', max_length=100),
        ),
    ]
