# Generated by Django 3.1.7 on 2021-05-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pki_framework', '0005_auto_20210508_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aerobridgecredential',
            name='association',
            field=models.IntegerField(choices=[(0, 'DIGITAL SKY OPERATOR'), (1, 'DIGITAL SKY MANUFACTURER'), (2, 'DIGITAL SKY PILOT'), (3, 'RFM'), (4, 'DSC / eMudra Token')], default=4),
        ),
    ]
