# Generated by Django 3.2.4 on 2021-06-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pki_framework', '0006_auto_20210520_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aerobridgecredential',
            name='token_type',
            field=models.IntegerField(choices=[(0, 'PUBLIC_KEY'), (1, 'PRIVATE_KEY'), (2, 'AUTHENTICATION TOKEN'), (3, 'OTHER')]),
        ),
    ]
