# Generated by Django 3.2.4 on 2021-06-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pki_framework', '0007_alter_aerobridgecredential_token_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aerobridgecredential',
            name='association',
            field=models.IntegerField(choices=[(0, 'DIGITAL SKY OPERATOR'), (1, 'DIGITAL SKY MANUFACTURER'), (2, 'DIGITAL SKY PILOT'), (3, 'RFM'), (4, 'DSC / eMudra Token')], default=4, help_text='Set the entity this credential is associated with. The association will be used when calling Digital Sky and other external servers'),
        ),
        migrations.AlterField(
            model_name='aerobridgecredential',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Set whether the credential is still active'),
        ),
        migrations.AlterField(
            model_name='aerobridgecredential',
            name='name',
            field=models.CharField(help_text='Enter a friendly name / description for the type of credential you are storing', max_length=100),
        ),
        migrations.AlterField(
            model_name='aerobridgecredential',
            name='token_type',
            field=models.IntegerField(choices=[(0, 'PUBLIC_KEY'), (1, 'PRIVATE_KEY'), (2, 'AUTHENTICATION TOKEN'), (3, 'OTHER')], help_text='Set the type of credential this is'),
        ),
    ]
