# Generated by Django 3.2.4 on 2021-06-25 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0051_auto_20210623_1241'),
        ('pki_framework', '0008_auto_20210617_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='aerobridgecredential',
            name='aircraft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.aircraft'),
        ),
        migrations.AddField(
            model_name='aerobridgecredential',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.manufacturer'),
        ),
        migrations.AddField(
            model_name='aerobridgecredential',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.operator'),
        ),
        migrations.AlterField(
            model_name='aerobridgecredential',
            name='association',
            field=models.IntegerField(choices=[(0, 'OPERATOR'), (1, 'MANUFACTURER'), (2, 'PILOT'), (3, 'RFM'), (4, 'DSC / eMudra Token')], default=4, help_text='Set the entity this credential is associated with. The association will be used when calling Digital Sky and other external servers'),
        ),
        migrations.AlterField(
            model_name='aerobridgecredential',
            name='token_type',
            field=models.IntegerField(choices=[(0, 'PUBLIC_KEY'), (1, 'PRIVATE_KEY'), (2, 'AUTHENTICATION TOKEN'), (3, 'OTHER'), (4, 'DIGITAL_CERTIFICATE')], help_text='Set the type of credential this is, e.g Public / Private Key'),
        ),
    ]
