# Generated by Django 3.2.5 on 2021-07-06 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pki_framework', '0009_auto_20210625_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aerobridgecredential',
            name='name',
            field=models.CharField(help_text='Enter a friendly name / description for the type of credential you are storing', max_length=100, validators=[django.core.validators.RegexValidator(message='No special characters allowed in this field.', regex='^[-, ,_\\w]*$')]),
        ),
    ]
