# Generated by Django 3.1.3 on 2020-11-23 16:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drone_type_id', models.IntegerField(choices=[(0, 'Quadcopter'), (1, 'Fixed Wing')], default=0)),
                ('version', models.CharField(default='00000', max_length=5)),
                ('device_id', models.CharField(default='00000000-0000-0000-0000-000000000000', max_length=64)),
                ('device_model_id', models.CharField(max_length=64)),
                ('operator_business_id', models.CharField(default=None, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prefix', models.CharField(default='', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcs_operations.drone')),
            ],
        ),
    ]
