# Generated by Django 3.2.8 on 2021-11-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcs_operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightplan',
            name='geo_json',
            field=models.JSONField(default=dict, help_text='Paste the flight plan as GeoJSON'),
        ),
    ]
