# Generated by Django 4.0.2 on 2022-03-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcs_operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightpermission',
            name='geo_cage',
            field=models.JSONField(default=dict),
        ),
    ]
