# Generated by Django 3.1.3 on 2020-11-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcs_operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='device_id',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='drone',
            name='operator_business_id',
            field=models.CharField(default='ABC123', max_length=36),
        ),
        migrations.AlterField(
            model_name='drone',
            name='version',
            field=models.CharField(max_length=5),
        ),
    ]
