# Generated by Django 3.1.3 on 2020-11-28 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0017_auto_20201128_2326'),
        ('gcs_operations', '0003_auto_20201124_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='drone',
        ),
        migrations.AddField(
            model_name='transaction',
            name='aircraft',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Aircraft', to='registry.aircraft'),
        ),
        migrations.DeleteModel(
            name='Drone',
        ),
    ]
