# Generated by Django 3.1.3 on 2020-11-29 22:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0018_auto_20201129_2219'),
        ('gcs_operations', '0004_auto_20201128_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=140)),
                ('type_of_operation', models.CharField(max_length=140)),
                ('flight_termination_or_return_home_capability', models.BooleanField(default=1)),
                ('geo_fencing_capability', models.BooleanField(default=1)),
                ('detect_and_avoid_capability', models.BooleanField(default=0)),
                ('recurring_time_expression', models.CharField(default='0 0 0 ? * 1#1 *', max_length=50)),
                ('recurring_time_duration', models.IntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.aircraft')),
            ],
        ),
        migrations.CreateModel(
            name='FlightPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('details', models.TextField(null=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UINApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fee_details', models.CharField(max_length=140)),
                ('import_permission', models.URLField()),
                ('cin', models.URLField()),
                ('gst_in', models.URLField()),
                ('pan_card', models.URLField()),
                ('dot_permission', models.URLField()),
                ('security_clearance', models.URLField()),
                ('eta', models.URLField()),
                ('op_manual', models.URLField()),
                ('maintainence_guidelines', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.aircraft')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.operator')),
            ],
        ),
        migrations.CreateModel(
            name='FlightPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Operation', to='gcs_operations.flightoperation')),
            ],
        ),
        migrations.AddField(
            model_name='flightoperation',
            name='flight_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcs_operations.flightplan'),
        ),
    ]
