# Generated by Django 3.1.3 on 2020-11-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcs_operations', '0006_flightplan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightoperation',
            name='name',
            field=models.CharField(default='Flight Operation', max_length=20),
        ),
        migrations.AlterField(
            model_name='flightplan',
            name='name',
            field=models.CharField(default='Flight Plan', max_length=20),
        ),
    ]
