# Generated by Django 3.1.3 on 2020-11-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcs_operations', '0007_auto_20201130_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightoperation',
            name='purpose',
        ),
        migrations.AlterField(
            model_name='flightoperation',
            name='name',
            field=models.CharField(default='Flight Operation jardnr', max_length=20),
        ),
        migrations.AlterField(
            model_name='flightoperation',
            name='type_of_operation',
            field=models.IntegerField(choices=[(0, 'VLOS'), (1, 'BVLOS')], default=0),
        ),
        migrations.AlterField(
            model_name='flightplan',
            name='name',
            field=models.CharField(default='Flight Plan wmkkeb', max_length=20),
        ),
    ]
