# Generated by Django 3.1.3 on 2020-11-30 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0019_auto_20201130_1207'),
        ('gcs_operations', '0009_auto_20201130_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightoperation',
            name='name',
            field=models.CharField(default='Flight Operation zwmizl', max_length=20),
        ),
        migrations.AlterField(
            model_name='flightoperation',
            name='purpose',
            field=models.ForeignKey(default='7a875ff9-79ee-460e-816f-30360e0ac645', on_delete=django.db.models.deletion.CASCADE, to='registry.activity'),
        ),
        migrations.AlterField(
            model_name='flightplan',
            name='name',
            field=models.CharField(default='Flight Plan nabiwj', max_length=20),
        ),
    ]
