# Generated by Django 3.1.3 on 2020-11-30 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0019_auto_20201130_1207'),
        ('gcs_operations', '0010_auto_20201130_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightpermission',
            name='is_successful',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='flightoperation',
            name='name',
            field=models.CharField(default='Flight Operation pismzj', max_length=20),
        ),
        migrations.AlterField(
            model_name='flightoperation',
            name='purpose',
            field=models.ForeignKey(default='7a875ff9-79ee-460e-816f-30360e0ac645', help_text='To add additional categories, please add entries to the Activities table', on_delete=django.db.models.deletion.CASCADE, to='registry.activity'),
        ),
        migrations.AlterField(
            model_name='flightoperation',
            name='type_of_operation',
            field=models.IntegerField(choices=[(0, 'VLOS'), (1, 'BVLOS')], default=0, help_text='At the moment, only VLOS and BVLOS operations are supported, for other types of operations, please issue a pull-request'),
        ),
        migrations.AlterField(
            model_name='flightplan',
            name='name',
            field=models.CharField(default='Flight Plan rlieav', max_length=20),
        ),
    ]
