# Generated by Django 3.1.3 on 2020-12-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcs_operations', '0015_auto_20201130_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightpermission',
            name='artefact',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='uinapplication',
            name='counter',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='flightoperation',
            name='name',
            field=models.CharField(default='Flight Operation aikcsw', max_length=30),
        ),
        migrations.AlterField(
            model_name='flightplan',
            name='name',
            field=models.CharField(default='Flight Plan mudvax', max_length=30),
        ),
    ]
