# Generated by Django 3.1.5 on 2021-01-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcs_operations', '0021_auto_20210127_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightoperation',
            name='name',
            field=models.CharField(default='Flightugmxqp', max_length=30),
        ),
        migrations.AlterField(
            model_name='flightplan',
            name='name',
            field=models.CharField(default='Flightjgrxmc', max_length=30),
        ),
    ]
