# Generated by Django 3.1.6 on 2021-02-03 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcs_operations', '0025_firmware'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Firmware',
        ),
    ]
