# Generated by Django 3.1.6 on 2021-02-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcs_operations', '0026_delete_firmware'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightpermission',
            name='artefact',
            field=models.TextField(default='', help_text='If the text above is empty, permission artefact for this operation has not been received'),
        ),
    ]
