# Generated by Django 3.1.6 on 2021-02-04 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcs_operations', '0027_auto_20210204_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightplan',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='flightplan',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
