# Generated by Django 3.1.7 on 2021-03-28 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcs_operations', '0028_auto_20210204_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flightplan',
            old_name='details',
            new_name='geo_json',
        ),
    ]
