# Generated by Django 3.2 on 2021-05-05 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcs_operations', '0029_auto_20210410_2038'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UINApplication',
        ),
    ]
