# Generated by Django 3.2.1 on 2021-05-06 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcs_operations', '0030_delete_uinapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightoperation',
            name='detect_and_avoid_capability',
        ),
        migrations.RemoveField(
            model_name='flightoperation',
            name='flight_termination_or_return_home_capability',
        ),
        migrations.RemoveField(
            model_name='flightoperation',
            name='geo_fencing_capability',
        ),
        migrations.RemoveField(
            model_name='flightoperation',
            name='recurring_time_duration',
        ),
        migrations.RemoveField(
            model_name='flightoperation',
            name='recurring_time_expression',
        ),
    ]
