# Generated by Django 3.2.4 on 2021-06-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcs_operations', '0032_auto_20210524_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightlog',
            name='signed_log',
            field=models.URLField(help_text='Enter the URL of the Zip file that has the signed log.'),
        ),
    ]
