# Generated by Django 3.2.4 on 2021-06-29 12:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gcs_operations', '0033_alter_flightlog_signed_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', models.URLField(help_text='URL location of the file')),
                ('name', models.CharField(default='Uploaded File', help_text='Give name to this file e.g. Flight Log from Operation A on 21st Aug.', max_length=140)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='flightoperation',
            name='name',
            field=models.CharField(default='Medicine Delivery Operation', help_text='Give a friendly name for this operation', max_length=140),
        ),
        migrations.AlterField(
            model_name='flightplan',
            name='name',
            field=models.CharField(default='Delivery Plan', help_text='Give this flight plan a friendly name', max_length=140),
        ),
    ]
