# Generated by Django 3.2.4 on 2021-06-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcs_operations', '0034_auto_20210629_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudfile',
            name='upload_type',
            field=models.CharField(choices=[('logs', 'Logs'), ('documents', 'Documents'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
