# Generated by Django 3.2.6 on 2021-08-16 15:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gcs_operations', '0037_auto_20210802_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightlog',
            name='signed_log',
        ),
        migrations.CreateModel(
            name='SignedFlightLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signed_log', models.URLField(help_text='Enter the URL of the Zip file that has the signed log, signed by the drone private key.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signed_flight_log', to='gcs_operations.flightlog')),
            ],
        ),
    ]
