# Generated by Django 3.2.6 on 2021-08-25 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcs_operations', '0038_auto_20210816_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signedflightlog',
            old_name='log',
            new_name='raw_flight_log',
        ),
    ]
