# Generated by Django 3.2.6 on 2021-08-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcs_operations', '0039_rename_log_signedflightlog_raw_flight_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightoperation',
            name='is_editable',
            field=models.BooleanField(default=True),
        ),
    ]
