# Generated by Django 3.2.6 on 2021-09-01 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcs_operations', '0040_flightoperation_is_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightlog',
            name='is_editable',
            field=models.BooleanField(default=True, help_text='Set whether the flight log can be edited. Once the flight log has been signed raw flight log cannot be edited.'),
        ),
        migrations.AddField(
            model_name='flightplan',
            name='is_editable',
            field=models.BooleanField(default=True, help_text='Set whether the flight plan can be edited. Once the flight log has been signed a flight plan cannot be edited.'),
        ),
        migrations.AlterField(
            model_name='flightoperation',
            name='is_editable',
            field=models.BooleanField(default=True, help_text='Set whether the flight operation can be edited. Once the flight log has been signed a flight operation cannot be edited.'),
        ),
        migrations.AlterField(
            model_name='signedflightlog',
            name='raw_flight_log',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='raw_flight_log', to='gcs_operations.flightlog'),
        ),
        migrations.AlterField(
            model_name='signedflightlog',
            name='signed_log',
            field=models.TextField(help_text='Flight log signed by the drone private key'),
        ),
    ]
