# Generated by Django 3.2.7 on 2021-10-09 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcs_operations', '0042_alter_flightoperation_drone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightpermission',
            name='is_successful',
        ),
        migrations.AddField(
            model_name='flightpermission',
            name='json',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='flightpermission',
            name='operation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Operation', to='gcs_operations.flightoperation'),
        ),
    ]
