# Generated by Django 3.2.7 on 2021-10-09 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcs_operations', '0043_auto_20211009_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightpermission',
            name='artefact',
        ),
    ]
