# Generated by Django 4.0.6 on 2022-08-05 16:08

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gcs_operations', '0001_initial'),
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(help_text='Describe the event in detail')),
                ('new_status', models.PositiveIntegerField(choices=[(10, 'OK'), (50, 'Attention needed'), (55, 'Damaged'), (60, 'Destroyed'), (70, 'Lost'), (65, 'Rejected'), (85, 'Returned')], default=[60, 70, 65], validators=[django.core.validators.MinValueValidator(0)])),
                ('event_datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ForeignKey(help_text='Select the aircraft assocated with this event', on_delete=django.db.models.deletion.CASCADE, to='registry.aircraft', verbose_name='Impacted Aicraft')),
                ('flight_log', models.ForeignKey(blank=True, help_text='Associate a Flight Log with this incident', null=True, on_delete=django.db.models.deletion.CASCADE, to='gcs_operations.flightlog')),
                ('impacted_components', models.ManyToManyField(help_text='Associate the components associated with this event with this incident', to='registry.aircraftcomponent')),
            ],
        ),
    ]
